# Generated by Django 5.0.6 on 2024-07-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('isbn', 'isbn'), ('edition', 'edition')], max_length=100),
        ),
    ]
